### ISSUE TITLE
Nästan alla lösenord är sparade i klartext.

### ISSUE THREAD

**Issue by te4-gabriel-stark** [itggot-TE4/Log-O-Matic-WHIJO#37]
Detta tycker jag och Daniel Berg borde vara kriminellt, kanske något ni kan fixa?
Argumentet att det bara är dummydata håller inte eftersom att det är lika lätt att spara det hashat som i klartext, samt att om ni hashar det så kommer ni in i vanan att spara det korrekt. :)

## DOD
- Inga lösenord sparas i klartext.

**Comment by TE4-arvid-nilber** [comment]
👍 agree
