### ISSUE TITLE
Make site non-dependent on preserveState

### ISSUE THREAD

**Issue by TE4-jacob-lundberg** [itggot-TE4/Log-O-Matic-WHIJO#80]
**Describe the bug**
When entering the page/sub-pages for the first time the console outputs errors and nothing is rendered.

**To Reproduce**
1. Clear localstorage
2. Enter the page/sub-pages
3. Open the console
4. See error(s)

**Expected behavior**
The page should still work as normal even though it's the first time a browser enters the page.

**Additional context**
This is most likely due to dependency on preserveState within the modules and using the module's data to render. This might be fixed by simply designating more default values on the modules attributes.

**Comment by itggot-linus-styren** [comment]
State such as the following should not be stored in a persistent module:
```
public isLoading : boolean = false;
public failure : string = "";
```
